# Generated by Django 4.2.7 on 2024-09-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Congno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiennha', models.BigIntegerField(default=0)),
                ('tiennuoc', models.BigIntegerField(default=0)),
                ('tiendien', models.BigIntegerField(default=0)),
                ('trangthai', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiendienthangtruoc', models.BigIntegerField(default=0)),
                ('tiennuocthangtruoc', models.BigIntegerField(default=0)),
                ('tiendienthangnay', models.BigIntegerField(default=0)),
                ('tiennuocthangnay', models.BigIntegerField(default=0)),
                ('tiennha', models.BigIntegerField(default=0)),
                ('congno', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Congno', to='myhouse.congno')),
            ],
        ),
    ]
