# Generated by Django 4.2.7 on 2024-09-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myhouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phong',
            old_name='tiendienthangnay',
            new_name='sodienthangnay',
        ),
        migrations.RenameField(
            model_name='phong',
            old_name='tiendienthangtruoc',
            new_name='sodienthangtruoc',
        ),
        migrations.RenameField(
            model_name='phong',
            old_name='tiennuocthangnay',
            new_name='sonuocthangnay',
        ),
        migrations.RenameField(
            model_name='phong',
            old_name='tiennuocthangtruoc',
            new_name='sonuocthangtruoc',
        ),
    ]
